# Change this value when copying the template to another single-application project.
name: openblocks

services:
  app:
    image: ${REGISTRY}/${COMPOSE_PROJECT_NAME}/app:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - '1000:80'
